const mongoose = require('mongoose');

const safetyAssessmentSchema = new mongoose.Schema({
    user: { type: mongoose.Schema.Types.ObjectId, required: true, ref: 'User' },
    overallScore: { type: String, enum: ['Safe', 'Mild', 'Moderate', 'Severe'], default: 'Safe' },
    interactions: [{
        medicineA: { type: String },
        medicineB: { type: String },
        severity: { type: String, enum: ['Mild', 'Moderate', 'Severe'] },
        aiExplanation: { type: String }, // Gemini generated explanation
        recommendation: { type: String }
    }],
    duplicateTherapies: [{
        medicines: [{ type: String }],
        reason: { type: String }
    }],
    aiSafetySummary: { type: String }, // Overall summary generated by Gemini
    lastUpdated: { type: Date, default: Date.now }
}, { timestamps: true });

module.exports = mongoose.model('SafetyAssessment', safetyAssessmentSchema);
