import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { dateUtils } from './dateUtils';

export const generateDoctorReport = (user, summary, activeMedications, symptoms) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(139, 92, 246); // Purple
    doc.text("MediSync-AI", 14, 20);
    
    doc.setFontSize(16);
    doc.setTextColor(30, 41, 59); // Slate-800
    doc.text("Patient Health & Adherence Report", 14, 30);
    
    doc.setFontSize(11);
    doc.setTextColor(100, 116, 139); // Slate-500
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 38);
    
    // Patient Details
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text("Patient Information", 14, 50);
    doc.setFontSize(11);
    doc.text(`Name: ${user?.name || 'N/A'}`, 14, 58);
    doc.text(`Email: ${user?.email || 'N/A'}`, 14, 64);
    
    // KPIs Summary
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text("Adherence Summary (7 Days)", 14, 76);
    
    const kpiData = [
        ["Adherence Rate", `${summary?.kpis?.adherenceWeekly || 0}%`],
        ["Current Streak", `${summary?.kpis?.currentStreak || 0} days`],
        ["Doses Missed", `${summary?.missedDoses?.length || 0}`]
    ];
    
    doc.autoTable({
        startY: 82,
        head: [['Metric', 'Value']],
        body: kpiData,
        theme: 'grid',
        headStyles: { fillColor: [139, 92, 246] },
        styles: { fontSize: 10 }
    });
    
    // Active Medications
    let currentY = doc.lastAutoTable.finalY + 14;
    doc.setFontSize(14);
    doc.setTextColor(30, 41, 59);
    doc.text("Active Medications", 14, currentY);
    
    const medData = (activeMedications || []).map(med => [
        med.name,
        med.dosage,
        med.frequency,
        dateUtils.formatDate(med.startDate)
    ]);
    
    doc.autoTable({
        startY: currentY + 6,
        head: [['Medication', 'Dosage', 'Frequency', 'Start Date']],
        body: medData,
        theme: 'striped',
        headStyles: { fillColor: [71, 85, 105] },
        styles: { fontSize: 10 }
    });

    // Recent Symptoms (if available)
    if (symptoms && symptoms.length > 0) {
        currentY = doc.lastAutoTable.finalY + 14;
        
        // Add new page if close to bottom
        if (currentY > 250) {
            doc.addPage();
            currentY = 20;
        }

        doc.setFontSize(14);
        doc.setTextColor(30, 41, 59);
        doc.text("Recent Symptoms (Last 30 Days)", 14, currentY);
        
        const symptomData = symptoms.map(sym => [
            dateUtils.formatDate(sym.createdAt),
            sym.symptomName,
            sym.severity + '/10',
            sym.notes || 'None'
        ]);
        
        doc.autoTable({
            startY: currentY + 6,
            head: [['Date', 'Symptom', 'Severity', 'Notes']],
            body: symptomData,
            theme: 'striped',
            headStyles: { fillColor: [239, 68, 68] }, // Red for symptoms
            styles: { fontSize: 10 }
        });
    }
    
    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(10);
        doc.setTextColor(148, 163, 184);
        doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.getWidth() - 25, doc.internal.pageSize.getHeight() - 10);
        doc.text("This report is generated by MediSync-AI for clinical discussion purposes.", 14, doc.internal.pageSize.getHeight() - 10);
    }
    
    doc.save(`MediSync_Report_${user?.name?.replace(/\s+/g, '_') || 'Patient'}.pdf`);
};
